### PR TITLE
Bunch of QOL changes.

### PR DESCRIPTION
**Pull request by Megiryuu**
I added something to check if you misspelled it, something to install requests for you if not present on the system, and finally made it print nicer, easier to differentiate between items.

### CODE REVIEW

**Comment by Lennster1** [comment]
@Megiryuu imma do some testing on my end, also seems that the quick status sometimes is more accurate, sometimes isn't. any ideas why?

**Comment by Megiryuu** [comment]
Nope, might update at different times, the api usually updates every minute

**Comment by Lennster1** [comment]
@Megiryuu ah ok. nice QOL changes, really good.

**Comment by Lennster1** [comment]
@Megiryuu do you think we should add commas between units( (e.g; 400,500,33 coins) to make it easier to read? let me know
also great job bump
@outsparkled @Megiryuu thanks for all the stuff you guys have done, really appreciate it.

**Comment by Lennster1** [comment]
@Megiryuu added commas to separate units, updated commenting.

**Review by Lennster1 — APPROVED** [review]
I think these changes are good, you guys think ready to be merged
@Megiryuu 
@outsparkled ?

**Pull request merged**
