### PR TITLE
code cleanup

### PR DESCRIPTION
**Pull request by outsparkled**

### CODE REVIEW

**Review by Lennster1 — COMMENTED** [review]
This is actually really nice. Ill do some testing on my end, wow thanks for helping me.

**Comment by Lennster1** [comment]
Hmmmm, seems that it says getAndPrintPrice and sendConnectionInfo arent defined. Maybe you have to define them before using them?

**Comment by Lennster1** [comment]
> Hmmmm, seems that it says getAndPrintPrice and sendConnectionInfo arent defined. Maybe you have to define them before using them?

yeah seems like it ill fix it on my end then we can review it

**Comment by Lennster1** [comment]
I fixed and merged

**Comment by outsparkled** [comment]
> Hmmmm, seems that it says getAndPrintPrice and sendConnectionInfo arent defined. Maybe you have to define them before using them?

yeah sorry my brain was still in java mode
in python you have to define the before using them

**Comment by Lennster1** [comment]
> > Hmmmm, seems that it says getAndPrintPrice and sendConnectionInfo arent defined. Maybe you have to define them before using them?
> 
> yeah sorry my brain was still in java mode
> in python you have to define the before using them

no problem!

**Pull request merged**
